### ISSUE TITLE
Consider undefined variable as string

### ISSUE THREAD

**Issue by hginzel** [CZ-NIC/pyed#2]
Could bare words became strings (optionally, `-u, --unsafe` / `-x`)?
```pz GNU+s </proc/version```
will be interpreted as `GNU='GNU'` instead of an exception
```Exception: <class 'NameError'> name 'GNU' is not defined on line: Linux…```
Shell eats quotes, it is necessary to double them: `pz "'GNU'"+s </proc/version`.

**Comment by e3rd** [comment]
I'm sorry for such a late answer.

I put an effort into this but the amount of side effects is more than significant. What if the string contains space (casts SyntaxError instead of the NameError)? What if different runtime interpreter than bash is used? What if the interpreter does not run in the english language so that we cannot use the message to extract the false variable name?
I fear I would not be able to implement this in a reasonable time, sorry for that. (Pull requests still welcome.)
