### ISSUE TITLE
Optional tabulate function for tuple mode?

### ISSUE THREAD

**Issue by gitzdnex** [CZ-NIC/pyed#4]
Hello,

this look exactly what I need and it is quite simple to use and quick to install (just wget). Anyway I was trying several options and 

s=1,2,3

seems to be quite okay, but I think it should be improved with some option to call tabulate() at end or cmd option to make whole output table when string is tuple? I Understand that I can use formating, but for simple tables it could be be good to make some quick there automatically?

**Comment by e3rd** [comment]
Would you be so kind and provide a more detailed example of how the input and the output should look like? Thanks!

**Comment by gitzdnex** [comment]
Hello,

well I guess  something like this should be able to use  it to make simple tables with data; I guess some last command then should be called or pipe should be used on result data?

s = 1,2,3
(next line = 4,5,6)

```
=== === ===
1   2    3
4   5    6
=== === ===
```

**Comment by e3rd** [comment]
I suppose the best tool is `pip install tabulate` at https://github.com/astanin/python-tabulate

Apart from using it as a Python library, you can use it as a callable that way:

```bash
$ echo -e "20\n40\n25\n28" | pz 's = count, s, sum(numbers)/count'  | tabulate 
--  ---  -------
1,  20,  20
2,  40,  30
3,  25,  28.3333
4,  28,  28.25
--  ---  -------
```

Do you think the commas look bad? Since the `pz` library does not need any requirement, I do not want to require it. However, we have these options:

1. instead of a comma, use a tab to join tuples
```bash
$ echo -e "20\n40\n25\n28" | pz 's = count, s, sum(numbers)/count'  
1	20	20.0
2	40	30.0
3	25	28.333333333333332
4	28	28.25

$ echo -e "20\n40\n25\n28" | pz 's = count, s, sum(numbers)/count'  | tabulate 
-  --  -------
1  20  20
2  40  30
3  25  28.3333
4  28  28.25
-  --  -------

$ echo -e "20\n40\n25\n28" | pz 's = count, s, sum(numbers)/count'  | tabulate -f fancy_grid
╒═══╤════╤═════════╕
│ 1 │ 20 │ 20      │
├───┼────┼─────────┤
│ 2 │ 40 │ 30      │
├───┼────┼─────────┤
│ 3 │ 25 │ 28.3333 │
├───┼────┼─────────┤
│ 4 │ 28 │ 28.25   │
╘═══╧════╧═════════╛
```

2. Detect whether the tabulate library is present and use it automatically
```bash
$ echo -e "20\n40\n25\n28" | pz 's = count, s, sum(numbers)/count'
-  --  -------
1  20  20
2  40  30
3  25  28.3333
4  28  28.25
-  --  -------
```

3. Use a flag to enforce table by default
4. ... ?

Which way would you prefer and why? Thanks!

**Comment by e3rd** [comment]
No reaction, closing
